[target.thumbv7m-none-eabi]
rustflags = ["-C", "link-arg=-Tlink.x"]
# runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -gdb tcp::3333 -S -nographic -kernel target/thumbv7m-none-eabi/debug/os"
runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -kernel target/thumbv7m-none-eabi/debug/os"

[build]
target = "thumbv7m-none-eabi"
